CREATE TABLE
    ADMINISTRATOR (
        ID_ADMIN SERIAL,
        NAME_ADMIN VARCHAR(20) NOT NULL,
        EMAIL_ADMIN VARCHAR(50) UNIQUE NOT NULL,
        PASSWORD_ADMIN VARCHAR(20) NOT NULL,
        PRIMARY KEY (ID_ADMIN)
    );
