CREATE TABLE
    PRODUCT (
        ID_PRODUCT SERIAL,
        NAME_PRODUCT VARCHAR(40) NOT NULL,
        DESCRIPTION_PRODUCT VARCHAR(120) NOT NULL,
        PRICE_PRODUCT NUMERIC NOT NULL,
        CONSTRAINT CK_PRICE CHECK (PRICE_PRODUCT > 0),
        PRIMARY KEY (ID_PRODUCT)
    );
