CREATE TABLE
    PRODUCT (
        PRODUCT_ID SERIAL,
        PRODUCT_NAME VARCHAR(40) NOT NULL,
        PRODUCT_DESCRIPTION VARCHAR(120) NOT NULL,
        PRODUCT_PRICE NUMERIC NOT NULL,
        CONSTRAINT CK_PRICE (PRODUCT_PRICE > 0),
        PRIMARY KEY (PRODUCT_ID)
    );
