CREATE TABLE
    ADMINISTRATOR (
        ADMINISTRATOR_ID SERIAL,
        ADMINISTRATOR_NAME VARCHAR(20) NOT NULL,
        ADMINISTRATOR_EMAIL VARCHAR(50) UNIQUE NOT NULL,
        ADMINISTRATOR_PASSWORD VARCHAR(20) NOT NULL,
        PRIMARY KEY (ADMINISTRATOR_ID)
    );

INSERT INTO
    ADMINISTRATOR (ADMINISTRATOR_NAME, ADMINISTRATOR_EMAIL, ADMINISTRATOR_PASSWORD)
VALUES
    ('kactuswow', 'kactuswow@gmail.com', 'admin'),
    ('Yademir', 'yademir@gmail.com', 'admin'),
    ('wasa', 'wasa@gmail.com', 'admin');
