CREATE TABLE
    ADMINISTRATOR (
        ADMINISTRATOR_ID SERIAL,
        ADMINISTRATOR_NAME VARCHAR(20) NOT NULL,
        ADMINISTRATOR_EMAIL VARCHAR(50) UNIQUE NOT NULL,
        ADMINISTRATOR_PASSWORD VARCHAR(20) NOT NULL,
        PRIMARY KEY (ADMINISTRATOR_ID)
    );
